apiVersion: v1
kind: Secret
metadata:
  name: harbor-registry-secret
  namespace: eshelf
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-registry-secret
  namespace: eshelf-dev
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K

