apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eshelf

resources:
  - namespace.yaml
  - api-gateway-deployment.yaml
  - auth-service-deployment.yaml
  - book-service-deployment.yaml
  - user-service-deployment.yaml
  - ml-service-deployment.yaml

labels:
  app.kubernetes.io/name: eshelf
  app.kubernetes.io/managed-by: kustomize

