apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eshelf-dev

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: dev

replicas:
  - name: api-gateway
    count: 1
  - name: auth-service
    count: 1
  - name: book-service
    count: 1

images:
  - name: eshelf/api-gateway
    newName: harbor-core.harbor.svc.cluster.local/eshelf/api-gateway
    newTag: dev
  - name: eshelf/auth-service
    newName: harbor-core.harbor.svc.cluster.local/eshelf/auth-service
    newTag: dev
  - name: eshelf/book-service
    newName: harbor-core.harbor.svc.cluster.local/eshelf/book-service
    newTag: dev
  - name: eshelf/user-service
    newName: harbor-core.harbor.svc.cluster.local/eshelf/user-service
    newTag: dev
  - name: eshelf/ml-service
    newName: harbor-core.harbor.svc.cluster.local/eshelf/ml-service
    newTag: dev

