apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eshelf-dev

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: dev

replicas:
  - name: api-gateway
    count: 1
  - name: auth-service
    count: 1
  - name: book-service
    count: 1

images:
  - name: eshelf/api-gateway
    newName: harbor.yourdomain.com/eshelf/api-gateway
    newTag: dev

