apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: user-service=harbor.yourdomain.com/eshelf/user-service
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/kustomize-image-name: user-service
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/eshelf-infra.git
    targetRevision: main
    path: infrastructure/kubernetes/overlays/prod
    kustomize:
      images:
        - name: user-service
          newName: harbor.yourdomain.com/eshelf/user-service
          newTag: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: eshelf-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

