apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
# ArgoCD Installation using official manifests
# This file references the official ArgoCD installation
# For actual installation, use:
# kubectl create namespace argocd
# kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

# Note: The actual installation should be done manually or via Helm
# This file is for reference only

